"""it exists now

Revision ID: 540228584e63
Revises: fa62379bc154
Create Date: 2023-08-08 12:15:48.668984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540228584e63'
down_revision = 'fa62379bc154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothing_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    # ### end Alembic commands ###
